services:
  api:
    depends_on:
      postgres:
        condition: service_healthy

    image: vigilant_waffle_api
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../api:/usr/src/app
    env_file:
      - .env

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
